[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "backend"
sourceDir = "backend-js"
startCommand = "npm start"
healthcheckPath = "/health"

[[services]]
name = "frontend"
sourceDir = "frontend"
startCommand = "npm start"
healthcheckPath = "/"

[[services]]
name = "admin"
sourceDir = "admin"
startCommand = "npm start"
healthcheckPath = "/"
