CREATE TABLE IF NOT EXISTS chat_rooms (
    id UUID PRIMARY KEY,
    stream_id UUID NOT NULL,
    chat_room_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (stream_id) REFERENCES streams(id) ON DELETE CASCADE
); 