CREATE TABLE IF NOT EXISTS videos (
    id UUID PRIMARY KEY,
    bunny_video_id VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    cdn_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 